"""JSON Intent payload schema and network request models.

The LLM never executes code directly — it emits a structured
``ActionIntent`` that is validated against these Pydantic models
before being forwarded to OPA for policy evaluation.
"""

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, Field


class ActionType(str, Enum):
    """Allowed browser action types."""

    CLICK = "click"
    FILL = "fill"
    NAVIGATE = "navigate"
    SUBMIT = "submit"
    SELECT = "select"
    HOVER = "hover"
    SCROLL = "scroll"
    WAIT = "wait"


class ActionIntent(BaseModel):
    """Structured intent that the Executor Agent produces.

    This payload is the *only* thing the LLM is allowed to output;
    raw Playwright calls are never generated by the LLM directly.
    """

    action: ActionType
    selector: str = Field(
        default="",
        description="CSS/XPath selector of the target element (empty for navigate/wait)",
    )
    value: str = Field(
        default="",
        description="Value to fill / URL to navigate to / option to select",
    )
    target_url: str = Field(
        default="",
        description="The URL the action targets (populated for navigate/submit)",
    )
    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Arbitrary extra context (e.g., element accessibility role)",
    )

    # Populated by the defense layer, not the LLM
    is_hidden_element: bool = Field(
        default=False,
        description="Flag set by the sanitizer if the target element was hidden",
    )
    current_page_origin: str = Field(
        default="",
        description="Origin of the page when the intent was generated",
    )


class NetworkRequest(BaseModel):
    """Model representing an intercepted outbound network request."""

    method: str = Field(description="HTTP method (GET, POST, PUT, …)")
    url: str = Field(description="Full request URL")
    headers: dict[str, str] = Field(default_factory=dict)
    body: str | None = Field(
        default=None,
        description="Request body (if present)",
    )
    body_size: int = Field(
        default=0,
        description="Size of the request body in bytes",
    )
    resource_type: str = Field(
        default="other",
        description="Playwright resource type (document, xhr, fetch, …)",
    )


class OPAInput(BaseModel):
    """Combined payload sent to OPA for policy evaluation."""

    action_intent: ActionIntent | None = None
    network_request: NetworkRequest | None = None
    allowed_domains: list[str] = Field(default_factory=list)
    max_outbound_body_bytes: int = 4096


class OPAResult(BaseModel):
    """Response from OPA policy evaluation."""

    allow: bool = False
    reasons: list[str] = Field(
        default_factory=list,
        description="Human-readable reasons for allow/deny",
    )
